# Generated by Django 3.2 on 2021-04-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrdWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('drupal_hash', models.CharField(max_length=250, unique=True)),
                ('drupal_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrdManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('drupal_hash', models.CharField(max_length=250, unique=True)),
                ('drupal_json', models.JSONField(blank=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiv.frdwork')),
            ],
        ),
    ]
