# Generated by Django 3.2 on 2021-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frdmanifestation',
            old_name='title',
            new_name='title_slug',
        ),
        migrations.RenameField(
            model_name='frdwork',
            old_name='title',
            new_name='title_slug',
        ),
        migrations.AddField(
            model_name='frdmanifestation',
            name='tei_doc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
