# Generated by Django 3.2 on 2021-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_auto_20210430_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='frdmanifestation',
            name='save_path',
            field=models.CharField(blank=True, max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='frdwork',
            name='save_path',
            field=models.CharField(blank=True, max_length=550, null=True, unique=True),
        ),
    ]
