# Generated by Django 3.2 on 2021-05-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_auto_20210502_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrdCollation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collation_html', models.TextField(blank=True, null=True)),
                ('collation_tei', models.TextField(blank=True, null=True)),
                ('collation_json', models.JSONField(blank=True, null=True)),
                ('manifestation', models.ManyToManyField(to='archiv.FrdManifestation')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiv.frdwork')),
            ],
        ),
    ]
