# Generated by Django 3.2 on 2021-05-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_frdcollation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrdCollationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slug', models.CharField(max_length=250, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('parent_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archiv.frdcollation')),
            ],
        ),
    ]
