# Generated by Django 3.2 on 2021-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_frdcollationsample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frdcollationsample',
            old_name='data',
            new_name='data_html',
        ),
        migrations.RemoveField(
            model_name='frdcollation',
            name='collation_html',
        ),
        migrations.RemoveField(
            model_name='frdcollation',
            name='collation_json',
        ),
        migrations.RemoveField(
            model_name='frdcollation',
            name='collation_tei',
        ),
        migrations.AddField(
            model_name='frdcollationsample',
            name='data_tei',
            field=models.TextField(blank=True, null=True),
        ),
    ]
