# Generated by Django 3.2 on 2021-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0006_auto_20210503_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='frdwork',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
