# Generated by Django 3.2 on 2021-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recogito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recogitoannotation',
            name='re_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
